### ISSUE TITLE
How to scroll to top?

### ISSUE THREAD

**Issue by starman1108** [bawn/Aquaman#10]
I think as following.
`mainScrollview.setContentOffset(.zero, animated: true)`

But it is not working.

**Comment by bawn** [comment]
```
pageViewController.mainScrollView.setContentOffset(.zero, animated: true)
childScrollView.setContentOffset(.zero, animated: true)
```

**Comment by starman1108** [comment]
Thank you for your answer.

`childScrollView `is not found. So instead of `childScrollView`, I used `currentChildScrollView`.
(I changed `currentChildScrollView`'s accessor '`internal`' to '`public`')

```
pageViewController.currentChildScrollView!.setContentOffset(.zero, animated: true)
pageViewController.mainScrollView.setContentOffset(.zero, animated: true)
```

But it does not scoll to top at once. It need two action for scroll to the top

So I try as following.
```
pageViewController.currentChildScrollView!.setContentOffset(.zero, animated: true)
DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
    pageViewController.mainScrollView.setContentOffset(.zero, animated: true)
}
```

It is working, but scrollToTop animation is paused for a while.

Any idea?

Thank you

**Comment by bawn** [comment]
You can get childScrollView at AquamanChildViewController.

>But it does not scoll to top at once. It need two action for scroll to the top

Aquaman's current implementation cannot achieve smooth animation. Try [Shazam](https://github.com/bawn/Shazam)

**Comment by starman1108** [comment]
If I use Shazam, does it have  this feature 'ScrollToTop'.

**Comment by bawn** [comment]
Yes, but Shazam has other bugs I haven’t solved. So it is recommended that you use Aquaman.

**Comment by bawn** [comment]
Or convince your product manager to accept this fact

**Comment by starman1108** [comment]
Thank you. I will try again.

**Comment by bawn** [comment]
Scroll to top function has been added.

```
public func scrollToTop(_ animation: Bool)
```

**Comment by starman1108** [comment]
You are awesome. Thank you very much.!!!
