### ISSUE TITLE
mainScrollView手势和childScrollView手势冲突

### ISSUE THREAD

**Issue by yangguangbiao** [bawn/Aquaman#2]
有时候下拉childScrollView时，无法切换到mainScrollView 下拉，而是进入到childScrollView bounces回弹状态，如果设置了childScrollView.alwaysBounceVertical = false，则没有这个问题。

**Comment by bawn** [comment]
@yangguangbiao  能描述下操作步骤吗，什么方式比较容易重现

**Comment by yangguangbiao** [comment]
进入Wonder Women, 当menuView悬停时，向左滑动一点点，不要滑动别的界面，然后下拉，就会出现这个bug。
下面是修复的代码：
        if childScrollViewObservations.count >= 3 {
            childScrollViewObservations.forEach { (obser) in
                obser.invalidate()
            }
            childScrollViewObservations.removeAll()
        }
        let keyValueObservation = scrollView.observe(\.contentOffset, options: [.new, .old], changeHandler: { [weak self] (scrollView, change) in
            print("ygbtest:11111")
            guard let self = self, change.newValue != change.oldValue else {
                return
            }
            self.childScrollViewDidScroll(scrollView)
        })
        childScrollViewObservations.append(keyValueObservation)

**Comment by bawn** [comment]
感谢提供的信息
