### ISSUE TITLE
大哥，bug来了，1.快速左右滑动闪退；2.上下多次滑动, current contentScrollView会出现偏移值不准确

### ISSUE THREAD

**Issue by yangguangbiao** [bawn/Aquaman#3]
修复代码
1.
func updateLayout(_ externalScrollView: UIScrollView) {
        
        let scrollViewWidth = externalScrollView.bounds.width
        let offsetX = externalScrollView.contentOffset.x
        let index = Int(offsetX / scrollViewWidth)
        guard index >= 0
            , index < stackView.arrangedSubviews.count else {
                return
        }
        currentIndex = index
        
        scrollRate = (offsetX - CGFloat(currentIndex) * scrollViewWidth) / scrollViewWidth
        let currentWidth = stackView.arrangedSubviews[currentIndex].bounds.width
        let leadingMargin = stackView.arrangedSubviews[currentIndex].frame.midX
        
        progressView.snp.updateConstraints { (make) in
            make.width.equalTo(widthDifference * scrollRate + currentWidth)
            make.centerX.equalTo(scrollView.snp.leading).offset(leadingMargin + itemSpace * scrollRate)
        }
    }

2.
func showChildViewContoller
let scrollView = targetViewController.aquamanChildScrollView()
        
//        scrollView.am_originOffset = scrollView.contentOffset
        if mainScrollView.contentOffset.y < sillValue {
//            scrollView.contentOffset = scrollView.am_originOffset
            scrollView.am_isCanScroll = false
            mainScrollView.am_isCanScroll = true
        }

**Comment by bawn** [comment]
@yangguangbiao 第二个问题我没有复现，不过理论上以下代码确实可以不用调用

```swift
 scrollView.contentOffset = scrollView.am_originOffset
```

但是设置 am_originOffset 是必要的
```swift 
scrollView.am_originOffset = scrollView.contentOffset
```

**Comment by LucioLee** [comment]
第二个问题我也遇到了，如果页面A往上滑，顶部菜单吸附，切换到页面B，将顶部往下拉回来，回到页面A，页面A是禁止滑动的，顶部有一部分就永远显示不了了！

**Comment by bawn** [comment]
>页面A是禁止滑动的

这个是什么意思，整个情况是必现的吗

**Comment by LucioLee** [comment]
必现的，可以加一下你的联系方式吗？可以录个屏给你

**Comment by bawn** [comment]
要不直接发我邮件 lc5491137@gmail.com，另外你测试的版本是 0.0.5 吗？

**Comment by LucioLee** [comment]
发你邮箱了，请查收
