### ISSUE TITLE
头部高度变化如何更新

### ISSUE THREAD

**Issue by LucioLee** [bawn/Aquaman#4]
HeaderView的高度会随着操作发送变化，怎么动画顺滑地更新高度？

**Comment by bawn** [comment]
简单一点在 AquamanPageViewController.swift 中添加一个方法
```swift
 public func updateHeaderView() {
        headerViewHeight = headerViewHeightFor(self)
        headerViewConstraint?.constant = headerViewHeight
    }
```

然后
```swift
override func pageController(_ pageController: AquamanPageViewController, mainScrollViewDidScroll scrollView: UIScrollView) {
        print(scrollView.contentOffset)
        headerViewHeight -= scrollView.contentOffset.y
        updateHeaderView()
    }
```

不过你需要考虑的是 scrollView.contentOffset 同时也在变化

**Comment by LucioLee** [comment]
多谢！已经解决，只是希望从库的层面提供支持，不想改库
![image](https://user-images.githubusercontent.com/17737959/66824828-a5038d00-ef7b-11e9-94eb-1fcb8b9f0f92.png)

**Comment by LucioLee** [comment]
还有一个问题，menuViewPinHeight这个参数我理解上应该是对menuView吸附效果做一个附加偏移，我看Demo中这个值传了一个导航栏的高度，能不能在库里实现对safeArea的适配？

**Comment by bawn** [comment]
谢谢你的意见，后续我会考虑优化

**Comment by bawn** [comment]
@LucioLee 

> 还有一个问题，menuViewPinHeight这个参数我理解上应该是对menuView吸附效果做一个附加偏移，我看Demo中这个值传了一个导航栏的高度，能不能在库里实现对safeArea的适配？

已经实现
