### ISSUE TITLE
請問要如何得到真正的contentOffset?

### ISSUE THREAD

**Issue by hawkeye1026** [bawn/Aquaman#8]
在mainScrollViewDidScroll delegate印出contentOffset後，發現只要滾動超過header高度，回傳的值都會一樣，請問有辦法拿到包含childScrollView的contentOffset嗎？

**Comment by bawn** [comment]
暂时没有办法拿到，你可以在 AquamanChildViewController 里面的拿到

```
func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
}
```

**Comment by hawkeye1026** [comment]
了解，目前我是自己在AquamanPageViewController加一個delegate來回傳兩個scrollView的contentOffset總和，希望之後能更新提供類似的delegate接口取得總contentOffset，感謝！

![截圖 2021-04-08 下午1 45 01](https://user-images.githubusercontent.com/15240803/113974640-dc04e700-9870-11eb-92df-0c44e6ad2543.png)
